### ISSUE TITLE
Replace excel with json

### ISSUE THREAD

**Issue by osamaramihafez** [Quran-Journey/backend#100]
It's easier to interact with a json file rather than an excel sheet. For one thing, we won't need to use pandas, which is very expensive and hard to use within any environment (and difficult to set up within docker). Another reason is that we can easily interact with the json file and insert data directly into the psql db.

- [x] store data in json from db
- [ ] Use the [this file as a template](https://github.com/Quran-Journey/backend/blob/master/tests/setup.js) for inserting the data into the database.

**Comment by ibrahim681** [comment]
I made changes on the main branch. Wondering if you would prefer I create a pull request in Roots directory or add the file directly.
