### ISSUE TITLE
Get surah info by surah id

### ISSUE THREAD

**Issue by osamaramihafez** [Quran-Journey/backend#107]
as title.

**Comment by ibrahim681** [comment]
*change Surah-info endpoint url 
*add a method to get by Surah ID

**Comment by osamaramihafez** [comment]
Also, don't use any dashes in filename or routes. Use camelCase

**Comment by osamaramihafez** [comment]
Also, I noticed you'll need to do the same thing with the reflection endpoint. It should also be tied to the surah id
