### ISSUE TITLE
Migrate to Typescript

### ISSUE THREAD

**Issue by osamaramihafez** [Quran-Journey/backend#167]
Our project is currently a CommonJS project and needs to be migrated to typescript for maintainability.

Note: work should be continued off of branch QJB-124 as this is a continuation of #124 

The objective of this ticket is:
1. Fix all imports to use es6 imports
2. Ensure typing is added to all methods.
3. Ensure models in the /models folder are being used in their appropriate location in the Postgres service (i.e. based on the SQL file).
4. Ensure linting is included
5. Update package.json to use typescript commands
6. Include any other typescript changes that are required and document those changes and if / how these changes affect project execution.

**Comment by Mukai009** [comment]
Hi Osama Hafez
I can help you.
This is upwork profile link. https://www.upwork.com/freelancers/~01d30f330c56f38ba1
Please connect me on upwork or call me with +48459568891 on whasapp.

**Comment by thisisharsh7** [comment]
Hi, I want to work on this issue. Please assign it to me.

**Comment by SantoshKumar4547** [comment]
is there any chance to assign this task to me?
