### ISSUE TITLE
Download surah notes as PDF

### ISSUE THREAD

**Issue by SarahEddeb** [Quran-Journey/backend#41]
Give students the ability to download a pdf version of the lesson notes.

TODOs:
- [ ] Create a GET endpoint for surah notes
- [ ] Document the endpoint
- [ ] Create a test for the endpoint

**Comment by osamaramihafez** [comment]
Create a GET endpoint for surah notes

**Comment by osamaramihafez** [comment]
We'll actually deal with this later. Closing for now.
