### ISSUE TITLE
Implement Server Side Authentication On Using Firebase

### ISSUE THREAD

**Issue by safaal28** [Quran-Journey/backend#64]
Osama: 

> Single Sign-on with firebase will allow us to obtain a token (JWT) which we can use to authenticate on all servers (we should store the same secret key on all of the necessary servers).
> 
> See how this person's approach was similar and how the problem was solved:
> https://stackoverflow.com/questions/39375886/separate-authentication-server-for-users-and-apis/53732262
> 
> Tasks:
> 
> - [x] Create a firebase account for Quran Journey
> - [x] Connect Firebase to our project (see the tutorial in the comment below on how to do so)
> - [x] Clean up auth routes to ensure that everything works smoothly (you can completely erase these routes and rewrite them if necessary).
> 
> The rest of the tasks can be taken up in another issue

My response: 
I'll be taking on authentication and I'll look into the most appropriate method for our project. Although we originally chose Firebase, it's good to keep an open mind. There are other solutions such as: https://egghead.io/courses/build-a-react-app-with-authorization-and-authentication-using-aws-amplify-8bbacfe9

This article describes the pros and cons of each method. https://rapidfork.medium.com/aws-amplify-vs-google-firebase-306aaa24a399

Another comparison resource: https://bejamas.io/compare/aws-amplify-vs-firebase/
At the bottom of that page involves other authentication tools. As of now, assume I'll use Firebase unless the team sees that another technology is optimal.

**Comment by safaal28** [comment]
Osama: 

>  Create an authentication/authorization system specific for admin so that they can update the web app content.
> 
> The objective is to use the token from firebase for ourselves without having to create our own token. We need to tie the token to the admin user that we will need to add to the database when they create an account and are approved by another admin. Do not store the token in the db as it will expire, watch the video below for a good approach to the problem.
> 
> Suggestions:
> Use firebase to allow Oauth (SSO) with google accounts.
> 
> I think this was the same tutorial I used the first time:
> https://www.youtube.com/watch?v=kX8by4eCyG4
> 
> Some things I did during MAA (don't worry too much about this, but just a small reference):
> 
> https://github.com/Muslim-Athletic-Association/backend/commit/7961c07
> https://github.com/Muslim-Athletic-Association/backend/commit/79a54c3
> https://github.com/Muslim-Athletic-Association/backend/commit/976158b

**Comment by osamaramihafez** [comment]
@safaal28 let's stick to firebase as agreed insha'Allah
