### ISSUE TITLE
Create db Schema for backend

### ISSUE THREAD

**Issue by osamaramihafez** [Quran-Journey/backend#76]
Include all of the tables that are laid out in our ERD. You can see the ERD in the README.md

**Comment by Tahir001** [comment]
Quick question in Table SurahInfo, there is a field / column named Text, which is a Foreign Key (FK). What is the FK referring too?

**Comment by osamaramihafez** [comment]
I was copy/pasting tables. If something doesn't make sense make sure to fix it. It should just be normal text probably.
