### ISSUE TITLE
Surah Info for a specific surah

### ISSUE THREAD

**Issue by osamaramihafez** [Quran-Journey/backend#84]
- [ ] Get a specific type of introductory information for a surah (is this needed? Lower priority)
- [x] Get all of the introductory information about a surah
- [x] Create an introductory information section for a surah
- [x] Update an introductory information section for a surah
- [x] Delete an introductory information section for a surah

**Comment by ibrahim681** [comment]
I believe the ERD requires some tweaking as it relates to Surah Info relation. Implemented schema has more attributes.
